### ISSUE TITLE
Initialize repo

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#1]
### TODOs
- [x] decide for base technology setup
- [x] create starter files + push to repo
- [x] addd to readme some basic info
