### ISSUE TITLE
Check functionality under WSL!

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#10]
### DESC
- check if cli works under wsl

### TODOs
- [x] add in verification of wsl 
- [x] repair folder check for wsl? 
- [x] verify Ubutntu version (being LTS 20 or higher?)
