### ISSUE TITLE
Register script on pypi

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#12]
### DESC
- https://cylab.be/blog/31/publishing-your-python-project-to-the-pypi-repository
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#requirements-for-packaging-and-distributing
---------------------
### TODOs
- [x] add more info to the setup script
- [x] check how to install via pypi
- [x] test out installation from testpypi via "pip install -i https://test.pypi.org/simple/ bock" ---> this won't work because deps cannot be resolved from the testpypi instance!
- [x] fix installation error (error at including all of the needed dependencies to bock?)
