### ISSUE TITLE
use project-abbr to clone from zimlab??

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#13]
### TODOs
- [x] create own zimlab service class
- [x] add "hardcoded" zimlab rest paths 
- [x] clone from zimlab
- [x] etc.
