### ISSUE TITLE
add dos2unix repair?

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#15]
### DESC
- dos2unix on all files in the apache folder.

### TODOs
- [x] add service impl
- [x] add a meaningful command like repair?
- [ ] optionally only repair project abbreviation files? or specific file?
