### ISSUE TITLE
Clone templates files / copy to apache / autosetup xslt and css files.  

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#17]
### DESC
- idea is to let a script handle the setup process of a GAMS project.
- after cloning of repo check if project files are there -> if not ask if templates project files should be setup?

### TODOs
- [x] copy over from temp dir to project dir in apache
- [x] change file names according to project-abbr
- [x] open xslt files and change projectAbbr variable accordingly
