### ISSUE TITLE
Allow display of docker logs 

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#22]
### DESC
- handling logs via bock to simplify access?

### TODOS
- [x] add own service called "GamsLocalDocker"
- [x] add more description to the class
- [x] copy tree is weirdly nested inside the for loop ?
- [x] check if running --> allow to start via bock?
- [x] allow to access logs
- [x] allow to stop via bock?
