### ISSUE TITLE
Method to verifiy / validate gams-local setup

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#3]
### TODOs
- [x] validate root folder
- [ ] validate additional folder setup
- [ ] validate if gams local is actually running? (sending some requests?)
- [ ] test if locations like "lib" / "fonts" / "templates" are available via requests? -> display warning?
- [x] #16
- [ ] how to handle custom setup of gams folder locations.
- [x] #15
