### ISSUE TITLE
Register on pypi

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#32]
### DESC
- register stuff on pypi instead of testpypi

### TODOs
- [x] create pypi account
- [x] generate token
- [x] build bock
- [x] deploy to pypi
- [x] test out installation
- [x] ask julia to test out bock
