### ISSUE TITLE
Implement git pull on every bock start

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/bock#34]
### TODOs
- [x] add gams update command --> run git pull for gams docker folder
- [ ] run a git fetch / each time gams is started? 
- [ ] update bock from inside bock? - launch command for it? is this possible? run code that checks if newer version of bock is available

**Comment by Stoff-Sebi** [comment]
implemented
