### ISSUE TITLE
Test out simple click-library calls

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/bock#6]
### TODOs
- [ ] check how to call from cli the precompiled main class -> write down in readme some examples
- [ ] test out basic subcommand
- [ ] think about copy over code from johannes / like self signed https auth etc.
